require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QuitProfilesController do

  def mock_quit_profile(stubs={})
    @mock_quit_profile ||= mock_model(QuitProfile, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all quit_profiles as @quit_profiles" do
      QuitProfile.stub(:all) { [mock_quit_profile] }
      get :index
      assigns(:quit_profiles).should eq([mock_quit_profile])
    end
  end

  describe "GET show" do
    it "assigns the requested quit_profile as @quit_profile" do
      QuitProfile.stub(:find).with("37") { mock_quit_profile }
      get :show, :id => "37"
      assigns(:quit_profile).should be(mock_quit_profile)
    end
  end

  describe "GET new" do
    it "assigns a new quit_profile as @quit_profile" do
      QuitProfile.stub(:new) { mock_quit_profile }
      get :new
      assigns(:quit_profile).should be(mock_quit_profile)
    end
  end

  describe "GET edit" do
    it "assigns the requested quit_profile as @quit_profile" do
      QuitProfile.stub(:find).with("37") { mock_quit_profile }
      get :edit, :id => "37"
      assigns(:quit_profile).should be(mock_quit_profile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created quit_profile as @quit_profile" do
        QuitProfile.stub(:new).with({'these' => 'params'}) { mock_quit_profile(:save => true) }
        post :create, :quit_profile => {'these' => 'params'}
        assigns(:quit_profile).should be(mock_quit_profile)
      end

      it "redirects to the created quit_profile" do
        QuitProfile.stub(:new) { mock_quit_profile(:save => true) }
        post :create, :quit_profile => {}
        response.should redirect_to(quit_profile_url(mock_quit_profile))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quit_profile as @quit_profile" do
        QuitProfile.stub(:new).with({'these' => 'params'}) { mock_quit_profile(:save => false) }
        post :create, :quit_profile => {'these' => 'params'}
        assigns(:quit_profile).should be(mock_quit_profile)
      end

      it "re-renders the 'new' template" do
        QuitProfile.stub(:new) { mock_quit_profile(:save => false) }
        post :create, :quit_profile => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quit_profile" do
        QuitProfile.stub(:find).with("37") { mock_quit_profile }
        mock_quit_profile.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :quit_profile => {'these' => 'params'}
      end

      it "assigns the requested quit_profile as @quit_profile" do
        QuitProfile.stub(:find) { mock_quit_profile(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:quit_profile).should be(mock_quit_profile)
      end

      it "redirects to the quit_profile" do
        QuitProfile.stub(:find) { mock_quit_profile(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(quit_profile_url(mock_quit_profile))
      end
    end

    describe "with invalid params" do
      it "assigns the quit_profile as @quit_profile" do
        QuitProfile.stub(:find) { mock_quit_profile(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:quit_profile).should be(mock_quit_profile)
      end

      it "re-renders the 'edit' template" do
        QuitProfile.stub(:find) { mock_quit_profile(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quit_profile" do
      QuitProfile.stub(:find).with("37") { mock_quit_profile }
      mock_quit_profile.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the quit_profiles list" do
      QuitProfile.stub(:find) { mock_quit_profile }
      delete :destroy, :id => "1"
      response.should redirect_to(quit_profiles_url)
    end
  end

end
